name: Berkeley DB Setup

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make script executable
        run: chmod +x ./berkeley.sh
      - name: Install Berkeley DB 4.8
        run: sudo ./berkeley.sh
