name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby and cache gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          # Use Bundler to install gems into vendor/bundle (bundler-cache already helps)
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build Jekyll site
        run: |
          # Build output goes to _site by default; make sure your site source files (Gemfile, _config.yml) are present
          bundle exec jekyll build --destination _site

      - name: Verify build (list first lines)
        run: |
          echo "Built files:"
          find _site -maxdepth 2 -type f -print | sed -n '1,200p'
          if [ ! -f _site/index.html ]; then
            echo "ERROR: _site/index.html not found — Pages will return 404."
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
