name: M4 (NGC 6121) using the Noctua Sky API

on:
  workflow_dispatch:

jobs:
  generate-reference:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display runner info
        run: |
          echo "Runner: $RUNNER_NAME"
          uname -a
          node --version

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: M4 (NGC 6121) using the Noctua Sky API
        run: node .github/script/simulate_m4_stars.cjs
