name: NTP Setup
#--------------
on:
  workflow_dispatch:

jobs:
  setup-ntp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run NTP Setup Script
        run: sudo node .github/script/ntp.js
